config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'land#index', as: :land

    get '/config', to: 'config#edit'
    post '/config', to: 'config#update'
  end

  namespace :wiki do
    Wiki::Object.types_not_disabled
                .each_key(&method(:resources))

    get '/:id', to: 'intrinsics#show', 
      constraints: { id: Wiki::Sheet::Intrinsic::ROUTE_REGEX },
      as: :intrinsic

    root to: 'root#index'
  end

  get '/@:id', to: 'users#show', as: :user
  
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register',
    }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AncientScroll</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="<%= body_variables %>">
    <aside>
      <%= link_to 'TODO', class: 'brand' do %>
        <%= fa Wiki.config.primary_icon %>
      <% end %>

      <nav>
        <%= active_link_to 'Regions', wiki_regions_path %>
        <%= active_link_to 'Provinces', wiki_provinces_path if Wiki.config.provinces? %>
        <%= active_link_to 'Locations', wiki_locations_path %>
        <%#= active_link_to 'Quests', wiki_quests_path %>

        <%= divider %>

        <%= active_link_to 'Characters', wiki_characters_path %>
        <%= active_link_to 'Organizations', wiki_organizations_path %>
        <%= active_link_to 'Trainer Classes', wiki_trainer_classes_path %>

        <%= divider %>

        <%#= wiki_object_type_path_link('Pokémon', 'pokemon') %>
        <%#= wiki_object_type_path_link('Abilities') %>
        <%#= wiki_object_type_path_link('Moves') %>

        <%#= divider %>

        <%= active_link_to 'Wiki Home', wiki_intrinsic_path('home') %>
        <%= active_link_to 'Guidelines', wiki_intrinsic_path('guidelines') %>
        <%= active_link_to 'FAQ', wiki_intrinsic_path('faq') %>

        <%= active_link_to 'Adminland', admin_land_path if can_create_object? %>
        <%= active_link_to 'Creators', '/creators' %>
        <%= active_link_to 'Github', Wiki.config.github_url if Wiki.config.github_url %>
      </nav>

      <div class="me">
        <% if Current.user %>
          <%= link_to "@#{Current.user.username}", Current.user.path, class: 'username' %>
          <small><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></small>
        <% else %>
          <%= button_to 'Sign In', new_user_session_path, class: 'button--primary' %>
        <% end %>
      </div>
    </aside>

    <main>
      <div class="main__content">
        <%= yield %>
      </div>
    </main>
  </body>
</html>